export const pathname = {
    HOME: '/',
    EXPERIENCE: '/experience',
    FORGOT_PASSWORD: '/forgot-password',
    VERIFY_CODE: '/verify-code',
    PROFILE: '/profile',
    VERIFY_CODE_SUCCESFULLY: '/verify-code-succesfully',
    CHANGE_PASSWORD: '/change-password',
    UPLOADQUESTION: '/upload-question',
    COURSEINFORMATION: '/course-information',
    CREATECOURSE: '/create-course',
    EDITCOURSE: '/edit-course',
    EDITLESSON: '/edit-lesson',
    COURSEMANAGEMENT: '/course-management',
    LESSON: '/lesson',
    STORE: '/store',
    MYCOURSE: '/my-course',
    CHAT:"/chat",
    POST:"/post",
    POSTDETAIL:'/post-detail',
    CREATEPOST:"/create-post",
    LISTPOST:"/list-posts"
};
